services:
    app:
        build: .
        ports:
            - "4000:4000"
        container_name: app_zipcode
        volumes:
            - ~/appLogs:/usr/app/logs:rw
        command: npm run start
