services:
    app:
        build: .
        image: app_zipcode:1.0.0
        ports:
            - "4000:4000"
        container_name: app_zipcode
        volumes:
            - ~/appLogs:/usr/app/logs:rw
        command: npm run start
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://localhost:4000/v1/health"]
            interval: 30s
            timeout: 5s
            retries: 3
        user: "1000:1000"
